[package]
name = "mult_split"
version = "0.1.0"
edition = "2021"
authors = ["jojii <jojii [at) gmx,net"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
